version: '3.8'

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./../:/workspaces
    working_dir: /workspaces
    command: sleep infinity
    ports:
      - 3000:3000
    expose:
      - 3000
